### ISSUE TITLE
usb-v1.6.4-node-v72-linux-arm64.tar.gz cannot found?

### ISSUE THREAD

**Issue by fantasyjqc** [eschava/node-red-contrib-xiaomi-ble#31]
http 404 https://github.com/tessel/node-usb/releases/download/v1.6.4/usb-v1.6.4-node-v72-linux-arm64.tar.gz

npm install node-red-contrib-xiaomi-bleill resolveWithNewModule npm-normalize-package-bin@1.0.1 checking installable status

> usb@1.6.4 install /root/.node-red/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/b0d04e-usb-v1.6.4-node-v72-linux-arm64.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.4/usb-v1.6.4-node-v72-linux-arm64.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.4/usb-v1.6.4-node-v72-linux-arm64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.20.2 runtime=node arch=arm64 libc= platform=linux)
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 7, in <module>
    import ast
ImportError: No module named ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.1.0-aml-s905
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.node-red/node_modules/usb
gyp ERR! node -v v12.20.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

**Comment by eschava** [comment]
Please try instructions from https://stackoverflow.com/questions/59681355/node-red-node-install-error-gyp-failed-with-exit-code-1
